Master jisc (#820)
* LMS-2173: use php_obj to follow convention

* LMS-2186 moodle-logstore_xapi: update lang string.

* LMS-2173: Move to the appropriate scheduled task to be able to filter successful events.

* LMS-2186 moodle-logstore_xapi: performance update, move counter under the capability check.

* LMS-1692 moodle-logstore_xapi: add notifications.

* LMS-1626 moodle-logstore_xapi: change pagetype to report.

* LMS-1692 moodle-logstore_xapi: update lang string.

* LMS-1701 - Bugfix username search and eventcontext

* LMS-1701 - Bugfix update pagename

* LMS-2173: add data to the sent log when running in realtime mode

* LMS-1625 moodle-logstore_xapi: add require file function to function call, set page title.

* LMS-1625 moodle-logstore_xapi: collect defaults to the same place.

* LMS-1625 moodle-logstore_xapi: update send sql.

* LMS-1698: add login, course_viewed and logout messages, 10 rows each in logstore_xapi_log and logstore_xapi_failed_log

* LMS-1625 moodle-logstore_xapi: resolve moveback from historic table.

* LMS-1625 moodle-logstore_xapi: code styling.

* LMS-1625 moodle-logstore_xapi: update lang strings.

* LMS-1625 moodle-logstore_xapi: code styling.

* LMS-1625 moodle-logstore_xapi: reorganise solution.

* LMS-1625 moodle-logstore_xapi: remove event from failed log when it was added from historic.

* LMS-1625 moodle-logstore_xapi: update handling remove elements.

* LMS-1625 moodle-logstore_xpai: add send/resend labels.

* LMS-1698 - fix relative path to config.php as per Moodle Docs https://docs.moodle.org/dev/CLI_scripts\#CLI_SCRIPT_constant

* LMS-1698: Add quiz and forum post message types.

* LMS-1698: copyright message and require_once

* LMS-2023 moodle-ogstore_xapi: add unit test for moving elements back from failed logs.

* LMS-2023 moodle-ogstore_xapi: code styling.

* LMS-1698: create mod/assign submitted and mod/assign graded events

* LMS-1698: generate test users

* LMS-2173: Put get_successful_events in lib.php

* LMS-1698: do not unset these variables, used in mod_quiz

* LMS-1698: define the number of rows to generate as a constant and tidy up script complete message

* LMS-2173: add line space after global $DB;

* LMS-2173: refactor add_event_to_sent_log and use get_successful_events from lib.php in store.php

* LMS-2294 moodle-logstore_xapi: Skip insert from historical log if the record already being in the xapi logstore.

* LMS-1649 - Bugfix - setting per page results from 30 to 40

* LMS-2174: only show items not sent in historic log view.

* LMS-2174: only show items not sent in historic log view.

* LMS-2286 - update capability value

* LMS-2285 - move $pagename definition immediately after require_once; add missing admin_externalpage_setup() call to disable non-admin/guest access

* LMS-2307 - Emails will now send to non-users and config allows for whitespace when defining email addresses

* LMS-2174: optimisation using NOT EXISTS instead of NOT IN

* LMS-2307 - force emailstop = 0 and code reformat

* LMS-2307 - SQL tidy up and adding string

* LMS-2277 - Removing response from info column as this is output in full in the response column.

* LMS-2262 moodle-logstore_xapi: reset page number when filter is updated.

* LMS-1625 moodle-logstore_xapi: define errortypes.

* LMS-2285 moodle-logstore_xapi: add require login to the page and only admins allowed to see it.

* LMS-2261 moodle-logstore_xapi: handle pagination with form elements.

* LMS-2261 moodle-logstore_xapi: remove debug elements.

* LMS-2261 moodle-logstore_xapi: remove errortype definitions.

* LMS-2335 moodle-logstore_xapi: set resend element to false always by default.

* LMS-2293 - Improving transform error and adding constants

* LMS-2303 - Bugfix for missing contexts

* LMS-1708: Implement historical task execute

* LMS-2352: Remove reconciled cron sub-task

* LMS-2352: bump version number

* LMS-1708: refactor emit/failed and historic tasks and add common functions to lib.php

* LMS-1708: Add new constants for log source and pass type in emit_task.

* LMS-1708: change methods in lib.php to use logstore_xapi_ prefix.

* LMS-1708: correct function name in comment.

* LMS-1708: correct function name in comment.

* LMS-2356 - Removing reconciled task settings and strings

* LMS-1708: use of correct batch size for task and comment updates.

* LMS-1708: use param as table name

* LMS-1708: update version.php

* LMS-1708: remove unnecessary if

* LMS-2406 - Notification email rework, logic updated to only insert 1 row per user when notifications are sent

* LMS-2406 - Doc block and typo fix

* LMS-2406 - Testing bug fixes, adding renderer to handle mustache template

* LMS-2428 - Fixed capability check on report.php

* LMS-2441 - remove array_merge as it renumbers integer indexes; instead set each key explicitly

* LMS-2406 - Bug fixes, count will only count new failed events since last sent notification

* LMS-2491 moodle-logstore_xapi: add managehistoric behaviour.

* LMS-2491 moodle-logstore_xapi: remove extra line.

* LMS-2490 moodle-logstore_xapi: set capability for historical log.

* LMS-2490 moodle-logstore_xapi: add capability check to moveback.php

* LMS-2490 moodle-logstore_xapi: change has_capability to requiry_capability.

* LMS-2481 - Adding event types in moveback class

* LMS-2481 - Bugfix for failed task. Failed task now only resends from the XAPI_LOG table using the correct type

* LMS-2481 - Removing unused stdClass and tool_log\log\manager

* LMS-2481 - add constants from lib

* LMS-2481 - new lib function to infer type from table; use function in dataseeder to set correct type

* LMS-2525 moodle-logstore_xapi: add filters to resend statements.

* LMS-2525 moodle-logstore_xapi: update version number.

* LMS-2580: fix XAPI_IMPORT_TYPE_LIVE (0) type check

* LMS-2580: don't make these parameters optional, they are always called with parameters

* LMS-2580: remove default value for limitnum

* LMS-1698: add historical items to logstore_xapi_log with type XAPI_IMPORT_TYPE_HISTORIC

* LMS-1698: Use a correct table name but still swap it in insert_row.

* LMS-1698: add to logstore_standard_log to allow testers to select the entries from the historical log.

* LMS-2605: Fix 'Notification trigger limit not reached' even when there is more errors than threshold value.

* LMS-2609: LRS endpoint link on email not working should be LMS instance name/url

* LMS-2609: move links to improve readability

* LMS-2657 - send username in actor.account.name

* LMS-2589 moodle-logstore_xapi: add get_verb to utils.

* LMS-2589 moodle-logstore_xapi: update get_verb call.

* LMS-2589 moodle-logstore_xapi: reorganise get verb call, and add loggedin verb.

* LMS-2589 moodle-logstore_xapi: remove loggedin params and require lang.

* LMS-2668 reconcile loggedin event

* LMS-2669 - reconcile loggedout event

* LMS-2589 moodle-logstore_xapi: Capture due date in statement.object.definition.extensions.http://xapi.jisc.ac.uk/dueDate.

* LMS-2589 moodle-logstore_xapi: Populate context extention for vle_mod_id.

* LMS-2589 moodle-logstore_xapi: add duedate to course assignment.

* LMS-2590 moodle-logstore_xapi: add get_verb to assignment_graded..

* LMS-2590 moodle-logstore_xapi: add get_verb cases in alphabetic order.

* LMS-2592 moodle-logstore_xapi: add viewed case to get_verb.

* LMS-2592 moodle-logstore_xapi: add JISc specific activity type to the quizes.

* LMS-2592 moodle-logstore_xapi: add JISc specific activity type to the quizes.

* LMS-2593 moodle-logstore_xapi: add get_verb to attempt_submitted/handler.

* LMS-2592 moodle-logstore_xapi: add JISc specific activity type to the quizes.

* LMS-2592 moodle-logstore_xapi: add started case to get_verb.

* LMS-2592 moodle-logstore_xapi: add received case to get_verb and set JISC specific activity type to mod_quiz/attempt_reviewed function.

* LMS-2596 moodle-logstore_xapi: add viewed verb to the attempt_viewed function and set JISC specific activity type.

* LMS-2596 moodle-logstore_xapi: change JISC specific activity.

* LMS-2596 moodle-logstore_xapi: change JISC specific activity.

* LMS-2589 moodle-logstore_xapi: performance update, remove extra function call.

* LMS-2733 moodle-logstore_xapi: update deploy script to use latest stable node.

* LMS-2733 moodle-logstore_xapi: update deploy script to use latest node.

* LMS-2733 moodle-logstore_xapi: using Moodle 38 stable at Travis.

* LMS-2670 - Surfacing detailed transform error to response to be viewed in failed log

* LMS-2873 - sort the list of event contexts alphabetically

* LMS-2874 - update lang string

* LMS-2733 moodle-logstore_xapi: update lang file comments.

* LMS-2733 moodle-logstore_xapi: update moveback_failed_statements test file comments.

* LMS-2733 moodle-logstore_xapi: Closing brace was indented incorrectly.

* LMS-2733 moodle-logstore_xapi: at report.php are solved:
  47 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
  48 | ERROR   | [ ] Commas (,) must be followed by white space.
 217 | ERROR   | [x] Expected 1 space before "*"; 0 found
 217 | ERROR   | [x] Expected 1 space after "*"; 0 found
 226 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
 261 | ERROR   | [ ] Expected "if (...) {\n"; found "if (...){\n"

* LMS-2733 moodle-logstore_xapi: update license description at access.php.

* LMS-2733 moodle-logstore_xapi: remove white spaces at upgrade.php.

* LMS-2733 moodle-logstore_xapi: solve the following issues at the cli/testdataseeder.php:
   1 | ERROR   | [ ] The first thing in a PHP file must be the <?php tag.
   2 | ERROR   | [x] Additional whitespace found at start of file
  23 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
  24 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
  73 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
  73 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
  79 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
  79 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
  82 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
  82 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
  85 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
  85 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
 102 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
 102 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
 107 | ERROR   | [ ] Line exceeds maximum limit of 180 characters; contains 185 characters
 112 | ERROR   | [ ] Line exceeds maximum limit of 180 characters; contains 216 characters
 117 | WARNING | [ ] Line exceeds 132 characters; contains 151 characters
 122 | WARNING | [ ] Line exceeds 132 characters; contains 171 characters
 127 | ERROR   | [ ] Line exceeds maximum limit of 180 characters; contains 235 characters
 132 | ERROR   | [ ] Line exceeds maximum limit of 180 characters; contains 210 characters
 137 | ERROR   | [ ] Line exceeds maximum limit of 180 characters; contains 229 characters
 142 | WARNING | [ ] Line exceeds 132 characters; contains 179 characters
 158 | ERROR   | [ ] Variable "course_viewed" must not contain underscores.
 161 | ERROR   | [ ] Variable "course_viewed" must not contain underscores.
 186 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
 186 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
 192 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
 192 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
 217 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks

* LMS-2733 moodle-logstore_xapi: update comment at moveback.php.

* LMS-2733 moodle-logstore_xapi: remove unnecessary white space from store.php.

* LMS-2733 moodle-logstore_xapi: update comments in sendfailednotifications_task.php.

* LMS-2733 moodle-logstore_xapi: add MOODLE_INTERNAL into reportfilter_form.php.

* LMS-2733 moodle-logstore_xapi: remove require config from moveback class.

* LMS-2733 moodle-logstore_xapi: update comments on course_quiz activity..

* LMS-2733 moodle-logstore_xapi: solve the issue Line exceeds 132 characters; contains 140 characters.

* LMS-2733 moodle-logstore_xapi: solve lines expected maximum 132 characters.

* LMS-2733 moodle-logstore_xapi: remove extra white spaces in load_batch.php.

* LMS-2733 moodle-logstore_xapi: update comments in get_user function.

* LMS-2733 moodle-logstore_xapi: remove test file.

* LMS-2733 moodle-logstore_xapi: using print_r is commented out.

* LMS-2733 moodle-logstore_xapi: using print_r is commented out.

* LMS-2857 moodle-logstore_xapi: initial commit for failed report form test.

* LMS-2857 moodle-logstore_xapi: update moveback test after we introduced type handling in the tasks.

* LMS-2857 moodle-logstore_xapi: initial commit for history report form test.

* LMS-2857 moodle-logstore_xapi: add requires.

* LMS-2857 moodle-logstore_xapi: add form tests, move defined variable from report.php to lib.php.

* LMS-2857 moodle-logstore_xapi: remove unnecessary addition.

* LMS-2941 logstore_xapi: add userfullname to defaults.

* LMS-2940 logstore_xapi: add a day when datefrom and dateto is equal.

* LMS-2940 logstore_xapi: remove 1 sec..

* LMS-2881 - replace print_r() call with json_encode()

* LMS-2857 moodle-logstore_xapi: add missing docblocks.

* LMS-2857 moodle-logstore_xapi: add missing docblocks.

* LMS-2939 moodle-logstore_xapi: using formelements at dateto variable.

* LMS-2940 moodle-logstore_xapi: set date to to end of the day.

* LMS-2881 - reinstate logstore_xapi_decode_response

* LMS-2733 moodle-logstore_xapi: fix code styling.

* LMS-2733 moodle-logstore_xapi: fix code styling.

* LMS-3029 - Historic Report will not load results on initial visit

* LMS-3030 - Event name filters do not populate on historic until results are shown

* LMS-3030 - code tidy up, displaying event names again

* LMS-3030 - Only populating event contexts with query runs

* LMS-3030 - wrapping $canresenderrors in the $run if, adding full stop to comment

* LMS-3030 - code tidy up for displaying results

* LMS-1960 moodle-logstore_xapi: solve coding error.

coding_exception: Coding error detected, it must be fixed by a programmer: All dataobjects in insert_records() must have the same structure!

* LMS-1960 moodle-logstore_xapi: an extra event has been added to 3.9 at the autogenerated events.

* LMS-1960 moodle-logstore_xapi: code styling, update comments on get_verb function.

* LMS-1960 moodle-logstore_xapi: code styling, update comments in lib.php.

FILE: /home/travis/build/moodle/admin/tool/log/store/xapi/lib.php
----------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 13 WARNINGS AFFECTING 12 LINES
----------------------------------------------------------------------------------------------
  37 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 119 | WARNING | Inline comments must start with a capital letter, digit or 3-dots sequence
 123 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 127 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 130 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 216 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 236 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 239 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 242 | WARNING | Inline comments must start with a capital letter, digit or 3-dots sequence
 242 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 245 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 248 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
 253 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
----------------------------------------------------------------------------------------------

* LMS-1960 moodle-logstore_xapi: code styling, update comments in settings.php.

* LMS-1960 moodle-logstore_xapi: code styling, change xAPI comments.

* LMS-1960 moodle-logstore_xapi: add function description to setUp.

* LMS-1960 moodle-logstore_xapi: rename variable to generatedxapilog.

* LMS-3528 - add missing array assignment operator for $lang

* LMS-3528 - version bump

Co-authored-by: Gordon MacQueen <51955245+gordonmacqueen-lp@users.noreply.github.com>
Co-authored-by: Michael Lynn <michael.lynn@learningpool.com>
Co-authored-by: László Záborski <laszlo.zaborski@learningpool.com>
Co-authored-by: Stephen O'Hara <stephen.ohara@learningpool.com>
Co-authored-by: Stephen O'Hara <Patches-@users.noreply.github.com>
Co-authored-by: Gordon MacQueen <gordon.macqueen@learningpool.com>
Co-authored-by: László Záborski <lzabo@users.noreply.github.com>